[package]
name = "ccdu-remote"
description = "SSH agent protocol for ccdu remote scans"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ccdu-core = { path = "../ccdu-core" }

[lints]
workspace = true
